import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "@/components/page/header";
import Footer from "@/components/page/footer";
import { ClerkProvider } from "@clerk/nextjs";

const outfit = Outfit({subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Next JS Porto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${outfit.className} antialiased`}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
